import "server-only";

import type { Element, Root, RootContent } from "hast";
import { fromHtml } from "hast-util-from-html";
import { toString as hastToString } from "hast-util-to-string";
import { getSingletonHighlighter, type Highlighter } from "shiki";
import { visit } from "unist-util-visit";

// ROADMAP §1.5 X-09: dual themes through CSS variables, so one server-side
// rendering serves sepia, light and dark — see the `.shiki` rules next to
// the tokens in app/globals.css.
const THEMES = { light: "github-light", dark: "github-dark" } as const;

// The languages this project registers with Shiki up front. Anything a
// fenced block asks for outside this set (plus whatever aliases Shiki loads
// alongside them, e.g. registering "ts" also loads "typescript") falls back
// to plain text — never an error.
const REGISTERED_LANGS = [
  "ts",
  "tsx",
  "js",
  "jsx",
  "json",
  "bash",
  "sql",
  "rust",
  "python",
  "go",
  "kotlin",
  "java",
  "csharp",
  "yaml",
  "toml",
  "html",
  "css",
  "diff",
  "markdown",
  "dockerfile",
];

// One highlighter instance per process: Shiki's grammars and themes are
// expensive to compile, so every render in this Node process shares the
// same singleton instead of rebuilding it per request. It's created lazily,
// on the first document that actually contains a fenced code block.
let highlighterPromise: Promise<Highlighter> | null = null;
let loadedLangsCache: Set<string> | null = null;

function getHighlighter(): Promise<Highlighter> {
  if (!highlighterPromise) {
    highlighterPromise = getSingletonHighlighter({
      themes: [THEMES.light, THEMES.dark],
      langs: REGISTERED_LANGS,
    });
  }
  return highlighterPromise;
}

function resolveLang(rawLang: string | undefined, loaded: Set<string>): string {
  const lang = (rawLang ?? "").trim().toLowerCase();
  return lang && loaded.has(lang) ? lang : "text";
}

interface FencedCodeCandidate {
  parent: Element | Root;
  index: number;
  code: string;
  rawLang?: string;
}

/** Finds every `<pre><code class="language-x">` block. Exported for tests. */
export function findFencedCodeBlocks(tree: Root): FencedCodeCandidate[] {
  const candidates: FencedCodeCandidate[] = [];

  visit(tree, "element", (node, index, parent) => {
    if (node.tagName !== "pre" || !parent || index === undefined) return;
    const [only] = node.children;
    if (node.children.length !== 1 || only.type !== "element" || only.tagName !== "code") return;

    const classNames = (only.properties.className as string[] | undefined) ?? [];
    const languageClass = classNames.find((name) => name.startsWith("language-"));

    candidates.push({
      parent: parent as Element | Root,
      index,
      code: hastToString(only),
      rawLang: languageClass?.slice("language-".length),
    });
  });

  return candidates;
}

function buildWrapper(lang: string, highlightedPre: Element): Element {
  return {
    type: "element",
    tagName: "div",
    properties: { className: ["code-block"], dataLanguage: lang },
    children: [
      {
        type: "element",
        tagName: "div",
        properties: { className: ["code-block-header"] },
        children: [
          {
            type: "element",
            tagName: "span",
            properties: { className: ["code-block-lang"] },
            children: [{ type: "text", value: lang }],
          },
          {
            type: "element",
            tagName: "button",
            properties: {
              type: "button",
              className: ["code-block-copy"],
              dataCopyCode: "",
              ariaLabel: "Copy code",
            },
            children: [{ type: "text", value: "Copy" }],
          },
        ],
      },
      highlightedPre,
    ],
  };
}

/**
 * Rehype enrichment step: turns every Markstone-safe `<pre><code class="language-x">`
 * fenced block into a highlighted block with a header (language label, copy
 * button). Shiki runs here, at render time, on the server only — nothing in
 * this module reaches the browser. The markup it produces is generated by
 * us, not by the document.
 */
export function rehypeHighlightCode() {
  return async (tree: Root) => {
    const candidates = findFencedCodeBlocks(tree);
    if (candidates.length === 0) return;

    const highlighter = await getHighlighter();
    if (!loadedLangsCache) loadedLangsCache = new Set(highlighter.getLoadedLanguages());
    const loadedLangs = loadedLangsCache;

    for (const candidate of candidates) {
      const lang = resolveLang(candidate.rawLang, loadedLangs);
      const highlightedHtml = highlighter.codeToHtml(candidate.code, {
        lang,
        themes: THEMES,
        defaultColor: false,
      });

      const fragment = fromHtml(highlightedHtml, { fragment: true });
      const shikiPre = fragment.children.find(
        (child): child is Element => child.type === "element" && child.tagName === "pre",
      );
      if (!shikiPre) continue;

      const children = candidate.parent.children as RootContent[];
      children[candidate.index] = buildWrapper(lang, shikiPre);
    }
  };
}
